In [198]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer


In [199]:
# Sample 2D matricx data
x = [['Germany','Male'],['France','Female'],['Spain', 'Female'],[ 'Germany', 'Female']]
x = np.asarray(x)

In [200]:
# LabelEncoder on first column
labelEncoder_X_1 = LabelEncoder()
x[:, 0] = labelEncoder_X_1.fit_transform(x[:, 0])
print(x)

[['1' 'Male']
 ['0' 'Female']
 ['2' 'Female']
 ['1' 'Female']]


In [201]:
# LabelEncoder on second column
x[:, 1] = labelEncoder_X_1.fit_transform(x[:, 1])
print(x)

[['1' '1']
 ['0' '0']
 ['2' '0']
 ['1' '0']]


In [202]:
x = x.reshape(len(x),2)
print(x)

[['1' '1']
 ['0' '0']
 ['2' '0']
 ['1' '0']]


In [203]:
# OneHotEncoder on entire x In output - First 3 columns are country columns and last two are gender columns.
oneHotEncoder = OneHotEncoder(sparse = False)
x = np.asarray(oneHotEncoder.fit_transform(x))
print(x) 

[[0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0.]]
